// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Application.Tests.Features.Identity.Commands
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class DiscordSign_InFeature : object, global::Xunit.IClassFixture<DiscordSign_InFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Identity/Commands", "Discord sign-in", "  As a player\r\n  I want every Discord sign-in to reach the same account\r\n  So tha" +
                "t my characters and raid activity stay attached to one identity", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "DiscordSignIn.feature"
#line hidden
        
        public DiscordSign_InFeature(DiscordSign_InFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Identity/Commands/DiscordSignIn.feature.ndjson", 10);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A first sign-in registers the player")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Discord sign-in")]
        [global::Xunit.TraitAttribute("Description", "A first sign-in registers the player")]
        public async global::System.Threading.Tasks.Task AFirstSign_InRegistersThePlayer()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A first sign-in registers the player", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("One local user per Discord account", null, tagsOfRule);
#line 8
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
      await testRunner.WhenAsync("Discord account \"80351110224678912\" signs in as \"Arthas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
      await testRunner.ThenAsync("the sign-in succeeds with a new user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
      await testRunner.AndAsync("the user is added and committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A returning player reaches the same user")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Discord sign-in")]
        [global::Xunit.TraitAttribute("Description", "A returning player reaches the same user")]
        public async global::System.Threading.Tasks.Task AReturningPlayerReachesTheSameUser()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A returning player reaches the same user", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("One local user per Discord account", null, tagsOfRule);
#line 13
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
      await testRunner.GivenAsync("Discord account \"80351110224678912\" is registered as \"Arthas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 15
      await testRunner.WhenAsync("Discord account \"80351110224678912\" signs in as \"Arthas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
      await testRunner.ThenAsync("the sign-in returns the registered user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 17
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A returning player with a new display name is updated")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Discord sign-in")]
        [global::Xunit.TraitAttribute("Description", "A returning player with a new display name is updated")]
        public async global::System.Threading.Tasks.Task AReturningPlayerWithANewDisplayNameIsUpdated()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A returning player with a new display name is updated", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("One local user per Discord account", null, tagsOfRule);
#line 19
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 20
      await testRunner.GivenAsync("Discord account \"80351110224678912\" is registered as \"Arthas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
      await testRunner.WhenAsync("Discord account \"80351110224678912\" signs in as \"Arthas the Pure\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
      await testRunner.ThenAsync("the sign-in returns the registered user", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 23
      await testRunner.AndAsync("the registered user is updated and committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A failed commit is returned")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Discord sign-in")]
        [global::Xunit.TraitAttribute("Description", "A failed commit is returned")]
        public async global::System.Threading.Tasks.Task AFailedCommitIsReturned()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A failed commit is returned", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("One local user per Discord account", null, tagsOfRule);
#line 25
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 26
      await testRunner.GivenAsync("the commit will fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
      await testRunner.WhenAsync("Discord account \"80351110224678912\" signs in as \"Arthas\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
      await testRunner.ThenAsync("the sign-in fails with \"Commit.Failed\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="An invalid sign-in is rejected before the handler runs")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Discord sign-in")]
        [global::Xunit.TraitAttribute("Description", "An invalid sign-in is rejected before the handler runs")]
        [global::Xunit.InlineDataAttribute("", "Arthas", "DiscordUserId", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("not-a-number", "Arthas", "DiscordUserId", "5", new string[0])]
        [global::Xunit.InlineDataAttribute("1234567890123456789012", "Arthas", "DiscordUserId", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("80351110224678912", "", "DisplayName", "7", new string[0])]
        public async global::System.Threading.Tasks.Task AnInvalidSign_InIsRejectedBeforeTheHandlerRuns(string discordId, string displayName, string property, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("discordId", discordId);
            argumentsOfScenario.Add("displayName", displayName);
            argumentsOfScenario.Add("property", property);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An invalid sign-in is rejected before the handler runs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Only values Discord issues are accepted", null, tagsOfRule);
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
      await testRunner.WhenAsync(string.Format("a sign-in for Discord account \"{0}\" as \"{1}\" is validated", discordId, displayName), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
      await testRunner.ThenAsync(string.Format("the validation fails on \"{0}\"", property), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await DiscordSign_InFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await DiscordSign_InFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
