// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Domain.Tests.Features.Communities.Aggregates
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CommunityLinkingAndRolesFeature : object, global::Xunit.IClassFixture<CommunityLinkingAndRolesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Communities/Aggregates", "Community linking and roles", "  As a community Administrator\r\n  I want my Discord server linked once and my Dis" +
                "cord roles to give RaidManager roles\r\n  So that only the people Discord trusts m" +
                "anage our raids", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Community.feature"
#line hidden
        
        public CommunityLinkingAndRolesFeature(CommunityLinkingAndRolesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Communities/Aggregates/Community.feature.ndjson", 37);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Linking a server makes the installer its Administrator")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Linking a server makes the installer its Administrator")]
        public async global::System.Threading.Tasks.Task LinkingAServerMakesTheInstallerItsAdministrator()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Linking a server makes the installer its Administrator", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Adding the bot links a server and makes the installer its Administrator", null, tagsOfRule);
#line 8
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
      await testRunner.WhenAsync("a user links the Discord server \"123456789012345678\" named \"  Citadel Vanguard  \"" +
                        " on Icecrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 10
      await testRunner.ThenAsync("the community is named \"Citadel Vanguard\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 11
      await testRunner.AndAsync("the installer has every permission", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A server id that is not a snowflake is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A server id that is not a snowflake is rejected")]
        public async global::System.Threading.Tasks.Task AServerIdThatIsNotASnowflakeIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A server id that is not a snowflake is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Adding the bot links a server and makes the installer its Administrator", null, tagsOfRule);
#line 13
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 14
      await testRunner.WhenAsync("a user links the Discord server \"citadel\" named \"Citadel Vanguard\" on Icecrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
      await testRunner.ThenAsync("the community change is rejected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A blank name is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A blank name is rejected")]
        public async global::System.Threading.Tasks.Task ABlankNameIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A blank name is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Adding the bot links a server and makes the installer its Administrator", null, tagsOfRule);
#line 17
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 18
      await testRunner.WhenAsync("a user links the Discord server \"123456789012345678\" named \"   \" on Icecrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
      await testRunner.ThenAsync("the community change is rejected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A name longer than 100 characters is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A name longer than 100 characters is rejected")]
        public async global::System.Threading.Tasks.Task ANameLongerThan100CharactersIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A name longer than 100 characters is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Adding the bot links a server and makes the installer its Administrator", null, tagsOfRule);
#line 21
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
      await testRunner.WhenAsync("a user links a Discord server with a name of 101 characters", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 23
      await testRunner.ThenAsync("the community change is rejected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A new community has the two presets with their permissions")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A new community has the two presets with their permissions")]
        public async global::System.Threading.Tasks.Task ANewCommunityHasTheTwoPresetsWithTheirPermissions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A new community has the two presets with their permissions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Every community starts with the Officer and Raid leader presets", null, tagsOfRule);
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 28
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
                global::Reqnroll.Table table9 = new global::Reqnroll.Table(new string[] {
                            "role",
                            "permissions"});
                table9.AddRow(new string[] {
                            "Officer",
                            "ManageRaids, BuildRosters, RunRaidNight, ReviewConflicts"});
                table9.AddRow(new string[] {
                            "Raid leader",
                            "ManageRaids, BuildRosters, RunRaidNight"});
#line 29
      await testRunner.ThenAsync("the community\'s roles are", ((string)(null)), table9, "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mapping a Discord role reports a change")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Mapping a Discord role reports a change")]
        public async global::System.Threading.Tasks.Task MappingADiscordRoleReportsAChange()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mapping a Discord role reports a change", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 36
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
      await testRunner.WhenAsync("the Administrator maps the Discord role \"111\" to \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 39
      await testRunner.ThenAsync("the Discord role \"111\" gives \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 40
      await testRunner.AndAsync("the role mappings changed once", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Mapping the same role again changes nothing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Mapping the same role again changes nothing")]
        public async global::System.Threading.Tasks.Task MappingTheSameRoleAgainChangesNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Mapping the same role again changes nothing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 42
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 43
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 44
      await testRunner.AndAsync("the Discord role \"111\" gives \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
      await testRunner.WhenAsync("the Administrator maps the Discord role \"111\" to \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
      await testRunner.ThenAsync("the role mappings did not change", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="One Discord role can give both Officer and Raid leader")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "One Discord role can give both Officer and Raid leader")]
        public async global::System.Threading.Tasks.Task OneDiscordRoleCanGiveBothOfficerAndRaidLeader()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("One Discord role can give both Officer and Raid leader", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 48
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 49
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 50
      await testRunner.AndAsync("the Discord role \"111\" gives \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 51
      await testRunner.WhenAsync("the Administrator maps the Discord role \"111\" to \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 52
      await testRunner.ThenAsync("the Discord role \"111\" gives \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 53
      await testRunner.AndAsync("the Discord role \"111\" gives \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
      await testRunner.AndAsync("the community has 2 role mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
      await testRunner.AndAsync("the role mappings changed once", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A role the community doesn\'t have can\'t be mapped")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A role the community doesn\'t have can\'t be mapped")]
        public async global::System.Threading.Tasks.Task ARoleTheCommunityDoesntHaveCantBeMapped()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A role the community doesn\'t have can\'t be mapped", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 58
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
      await testRunner.WhenAsync("the Administrator maps the Discord role \"111\" to a role the community doesn\'t hav" +
                        "e", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
      await testRunner.ThenAsync("the community change is rejected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A role id that is not a snowflake is rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A role id that is not a snowflake is rejected")]
        public async global::System.Threading.Tasks.Task ARoleIdThatIsNotASnowflakeIsRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A role id that is not a snowflake is rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 62
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 63
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
      await testRunner.WhenAsync("the Administrator maps the Discord role \"officers\" to \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 65
      await testRunner.ThenAsync("the community change is rejected", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Removing a mapping reports a change")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Removing a mapping reports a change")]
        public async global::System.Threading.Tasks.Task RemovingAMappingReportsAChange()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Removing a mapping reports a change", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 68
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
      await testRunner.AndAsync("the Discord role \"111\" gives \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 70
      await testRunner.WhenAsync("the Administrator removes the \"Officer\" mapping of the Discord role \"111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 71
      await testRunner.ThenAsync("the community has 0 role mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 72
      await testRunner.AndAsync("the role mappings changed once", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Removing one of a Discord role\'s mappings keeps the other")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Removing one of a Discord role\'s mappings keeps the other")]
        public async global::System.Threading.Tasks.Task RemovingOneOfADiscordRolesMappingsKeepsTheOther()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Removing one of a Discord role\'s mappings keeps the other", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 74
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 75
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 76
      await testRunner.AndAsync("the Discord role \"111\" gives \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
      await testRunner.AndAsync("the Discord role \"111\" gives \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
      await testRunner.WhenAsync("the Administrator removes the \"Officer\" mapping of the Discord role \"111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
      await testRunner.ThenAsync("the Discord role \"111\" gives \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 80
      await testRunner.AndAsync("the community has 1 role mapping", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Removing a role that was not mapped changes nothing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Removing a role that was not mapped changes nothing")]
        public async global::System.Threading.Tasks.Task RemovingARoleThatWasNotMappedChangesNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Removing a role that was not mapped changes nothing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator maps Discord roles to the community\'s roles", null, tagsOfRule);
#line 82
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
      await testRunner.WhenAsync("the Administrator removes the \"Officer\" mapping of the Discord role \"111\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
      await testRunner.ThenAsync("the role mappings did not change", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Permissions add up across the member\'s roles")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Permissions add up across the member\'s roles")]
        [global::Xunit.InlineDataAttribute("111,222", "Officer, Raid leader", "ManageRaids, BuildRosters, RunRaidNight, ReviewConflicts", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("222", "Raid leader", "ManageRaids, BuildRosters, RunRaidNight", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("222,333", "Raid leader", "ManageRaids, BuildRosters, RunRaidNight", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("333", "", "None", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("", "", "None", "17", new string[0])]
        public async global::System.Threading.Tasks.Task PermissionsAddUpAcrossTheMembersRoles(string discordRoles, string roles, string permissions, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("discord roles", discordRoles);
            argumentsOfScenario.Add("roles", roles);
            argumentsOfScenario.Add("permissions", permissions);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Permissions add up across the member\'s roles", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A member has every role and permission their Discord roles give", null, tagsOfRule);
#line 89
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 90
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
      await testRunner.AndAsync("the Discord role \"111\" gives \"Officer\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 92
      await testRunner.AndAsync("the Discord role \"222\" gives \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
      await testRunner.WhenAsync(string.Format("a member has the Discord roles \"{0}\"", discordRoles), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 94
      await testRunner.ThenAsync(string.Format("the member\'s roles are \"{0}\"", roles), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 95
      await testRunner.AndAsync(string.Format("the member\'s permissions are \"{0}\"", permissions), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A created role goes to the end of the list with what it allows")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A created role goes to the end of the list with what it allows")]
        public async global::System.Threading.Tasks.Task ACreatedRoleGoesToTheEndOfTheListWithWhatItAllows()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A created role goes to the end of the list with what it allows", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 107
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 108
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
      await testRunner.WhenAsync("the Administrator creates the role \"  Veteran  \" allowing \"RunRaidNight\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 110
      await testRunner.ThenAsync("the role change succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table10 = new global::Reqnroll.Table(new string[] {
                            "role",
                            "permissions"});
                table10.AddRow(new string[] {
                            "Officer",
                            "ManageRaids, BuildRosters, RunRaidNight, ReviewConflicts"});
                table10.AddRow(new string[] {
                            "Raid leader",
                            "ManageRaids, BuildRosters, RunRaidNight"});
                table10.AddRow(new string[] {
                            "Veteran",
                            "RunRaidNight"});
#line 111
      await testRunner.AndAsync("the community\'s roles are", ((string)(null)), table10, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A role that can\'t be created is refused")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A role that can\'t be created is refused")]
        [global::Xunit.InlineDataAttribute("the Administrator", "", "RunRaidNight", "Community.RoleNameInvalid", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("the Administrator", "123456789012345678901234567890123456789012345678901", "RunRaidNight", "Community.RoleNameInvalid", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("the Administrator", "officer", "RunRaidNight", "Community.RoleNameTaken", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("the Administrator", "Veteran", "64", "Community.RolePermissionsInvalid", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("a role manager", "Council", "ManageCommunityRoles", "Community.CannotGrantRoleManagement", "23", new string[0])]
        public async global::System.Threading.Tasks.Task ARoleThatCantBeCreatedIsRefused(string who, string name, string permissions, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("who", who);
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("permissions", permissions);
            argumentsOfScenario.Add("error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A role that can\'t be created is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 117
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 118
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 119
      await testRunner.WhenAsync(string.Format("{0} creates the role \"{1}\" allowing \"{2}\"", who, name, permissions), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 120
      await testRunner.ThenAsync(string.Format("the role change fails with \"{0}\"", error), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Only the Administrator lets a role manage roles")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Only the Administrator lets a role manage roles")]
        public async global::System.Threading.Tasks.Task OnlyTheAdministratorLetsARoleManageRoles()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "24";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Only the Administrator lets a role manage roles", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 130
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 131
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 132
      await testRunner.WhenAsync("the Administrator creates the role \"Council\" allowing \"ManageCommunityRoles, Mana" +
                        "geRaids\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
      await testRunner.ThenAsync("the role change succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Changing a role renames it and changes what it allows")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Changing a role renames it and changes what it allows")]
        public async global::System.Threading.Tasks.Task ChangingARoleRenamesItAndChangesWhatItAllows()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "25";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Changing a role renames it and changes what it allows", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 135
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 136
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 137
      await testRunner.AndAsync("the Discord role \"222\" gives \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
      await testRunner.WhenAsync("the Administrator changes the role \"Raid leader\" to \"Raid lead\" allowing \"RunRaid" +
                        "Night\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 139
      await testRunner.ThenAsync("the role change succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 140
      await testRunner.AndAsync("the role mappings changed once", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 141
      await testRunner.AndAsync("a member with the Discord roles \"222\" may \"RunRaidNight\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A role keeps its own name when it changes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A role keeps its own name when it changes")]
        public async global::System.Threading.Tasks.Task ARoleKeepsItsOwnNameWhenItChanges()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "26";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A role keeps its own name when it changes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 143
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 144
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 145
      await testRunner.WhenAsync("the Administrator changes the role \"Officer\" to \"OFFICER\" allowing \"ManageRaids\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 146
      await testRunner.ThenAsync("the role change succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A role change that isn\'t allowed is refused")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A role change that isn\'t allowed is refused")]
        [global::Xunit.InlineDataAttribute("the Administrator", "Officer", "Raid leader", "ManageRaids", "Community.RoleNameTaken", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("the Administrator", "Ghost", "Ghost", "ManageRaids", "Community.RoleNotFound", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("a role manager", "Council", "Council", "ManageRaids", "Community.RoleLocked", "29", new string[0])]
        [global::Xunit.InlineDataAttribute("a role manager", "Officer", "Officer", "ManageCommunityRoles", "Community.CannotGrantRoleManagement", "30", new string[0])]
        public async global::System.Threading.Tasks.Task ARoleChangeThatIsntAllowedIsRefused(string who, string role, string name, string permissions, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("who", who);
            argumentsOfScenario.Add("role", role);
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("permissions", permissions);
            argumentsOfScenario.Add("error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A role change that isn\'t allowed is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 148
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 149
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 150
      await testRunner.AndAsync("the community has the role \"Council\" allowing \"ManageCommunityRoles\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 151
      await testRunner.WhenAsync(string.Format("{0} changes the role \"{1}\" to \"{2}\" allowing \"{3}\"", who, role, name, permissions), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 152
      await testRunner.ThenAsync(string.Format("the role change fails with \"{0}\"", error), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Deleting a role removes its mappings")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "Deleting a role removes its mappings")]
        public async global::System.Threading.Tasks.Task DeletingARoleRemovesItsMappings()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "31";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Deleting a role removes its mappings", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 161
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 162
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 163
      await testRunner.AndAsync("the Discord role \"222\" gives \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 164
      await testRunner.WhenAsync("the Administrator deletes the role \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 165
      await testRunner.ThenAsync("the role change succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 166
      await testRunner.AndAsync("the community has 0 role mappings", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 167
      await testRunner.AndAsync("a member with the Discord roles \"222\" may \"None\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A role deletion that isn\'t allowed is refused")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A role deletion that isn\'t allowed is refused")]
        [global::Xunit.InlineDataAttribute("the Administrator", "Ghost", "Community.RoleNotFound", "32", new string[0])]
        [global::Xunit.InlineDataAttribute("a role manager", "Council", "Community.RoleLocked", "33", new string[0])]
        public async global::System.Threading.Tasks.Task ARoleDeletionThatIsntAllowedIsRefused(string who, string role, string error, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("who", who);
            argumentsOfScenario.Add("role", role);
            argumentsOfScenario.Add("error", error);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A role deletion that isn\'t allowed is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 169
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 170
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 171
      await testRunner.AndAsync("the community has the role \"Council\" allowing \"ManageCommunityRoles\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 172
      await testRunner.WhenAsync(string.Format("{0} deletes the role \"{1}\"", who, role), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 173
      await testRunner.ThenAsync(string.Format("the role change fails with \"{0}\"", error), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A role manager deletes a role that doesn\'t manage roles")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Community linking and roles")]
        [global::Xunit.TraitAttribute("Description", "A role manager deletes a role that doesn\'t manage roles")]
        public async global::System.Threading.Tasks.Task ARoleManagerDeletesARoleThatDoesntManageRoles()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "34";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A role manager deletes a role that doesn\'t manage roles", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The Administrator and role managers shape the community\'s roles", null, tagsOfRule);
#line 180
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 181
      await testRunner.GivenAsync("a linked community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 182
      await testRunner.WhenAsync("a role manager deletes the role \"Raid leader\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 183
      await testRunner.ThenAsync("the role change succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CommunityLinkingAndRolesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CommunityLinkingAndRolesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
