// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Companion.Client.Tests.Features.Pairing
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CompanionPairingCheckWhileItRunsFeature : object, global::Xunit.IClassFixture<CompanionPairingCheckWhileItRunsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Pairing", "Companion pairing check while it runs", "  As a player\r\n  I want a computer I revoke to stop at once, even while its compa" +
                "nion runs\r\n  So that only the computers I keep paired upload for me", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CompanionPairingCheckWhileItRuns.feature"
#line hidden
        
        public CompanionPairingCheckWhileItRunsFeature(CompanionPairingCheckWhileItRunsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Pairing/CompanionPairingCheckWhileItRuns.feature.ndjson", 8);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A revocation shows at the next check")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing check while it runs")]
        [global::Xunit.TraitAttribute("Description", "A revocation shows at the next check")]
        [global::Xunit.InlineDataAttribute("299", "Paired", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("300", "Revoked", "1", new string[0])]
        public async global::System.Threading.Tasks.Task ARevocationShowsAtTheNextCheck(string seconds, string state, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("seconds", seconds);
            argumentsOfScenario.Add("state", state);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A revocation shows at the next check", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A paired companion checks its token every five minutes", null, tagsOfRule);
#line 8
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 9
      await testRunner.GivenAsync("a pairing for \"Bryn\" is stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 10
      await testRunner.AndAsync("RaidManager answers the token checks with \"Valid\" then \"Refused\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 11
      await testRunner.AndAsync("the companion has started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
      await testRunner.WhenAsync(string.Format("{0} seconds pass", seconds), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
      await testRunner.ThenAsync(string.Format("the companion shows \"{0}\"", state), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A check that can\'t reach RaidManager keeps the pairing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing check while it runs")]
        [global::Xunit.TraitAttribute("Description", "A check that can\'t reach RaidManager keeps the pairing")]
        public async global::System.Threading.Tasks.Task ACheckThatCantReachRaidManagerKeepsThePairing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A check that can\'t reach RaidManager keeps the pairing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A paired companion checks its token every five minutes", null, tagsOfRule);
#line 20
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 21
      await testRunner.GivenAsync("a pairing for \"Bryn\" is stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 22
      await testRunner.AndAsync("RaidManager answers the token checks with \"Valid\" then \"Unavailable\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 23
      await testRunner.AndAsync("the companion has started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 24
      await testRunner.WhenAsync("300 seconds pass", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
      await testRunner.ThenAsync("the companion shows \"Paired\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 26
      await testRunner.AndAsync("the stored pairing is \"kept\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A computer just paired with a code is checked too")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing check while it runs")]
        [global::Xunit.TraitAttribute("Description", "A computer just paired with a code is checked too")]
        public async global::System.Threading.Tasks.Task AComputerJustPairedWithACodeIsCheckedToo()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A computer just paired with a code is checked too", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A paired companion checks its token every five minutes", null, tagsOfRule);
#line 28
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 29
      await testRunner.GivenAsync("RaidManager answers with the code \"K7M-4QX\" valid for 10 minutes and a polling in" +
                        "terval of 5 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 30
      await testRunner.AndAsync("\"Bryn\" confirms the code before the first poll", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 31
      await testRunner.AndAsync("RaidManager answers the token checks with \"Refused\" then \"Refused\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
      await testRunner.AndAsync("the companion shows the code", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
      await testRunner.WhenAsync("305 seconds pass", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 34
      await testRunner.ThenAsync("the companion shows \"Revoked\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Opening a revoked companion shows it at once")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing check while it runs")]
        [global::Xunit.TraitAttribute("Description", "Opening a revoked companion shows it at once")]
        public async global::System.Threading.Tasks.Task OpeningARevokedCompanionShowsItAtOnce()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Opening a revoked companion shows it at once", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Opening the companion checks its token at once", null, tagsOfRule);
#line 38
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 39
      await testRunner.GivenAsync("a pairing for \"Bryn\" is stored", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
      await testRunner.AndAsync("RaidManager answers the token checks with \"Valid\" then \"Refused\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 41
      await testRunner.AndAsync("the companion has started", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 42
      await testRunner.WhenAsync("the player opens the companion", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 43
      await testRunner.ThenAsync("the companion shows \"Revoked\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 44
      await testRunner.AndAsync("the stored pairing is \"deleted\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Opening a companion that isn\'t paired checks nothing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing check while it runs")]
        [global::Xunit.TraitAttribute("Description", "Opening a companion that isn\'t paired checks nothing")]
        public async global::System.Threading.Tasks.Task OpeningACompanionThatIsntPairedChecksNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Opening a companion that isn\'t paired checks nothing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Opening the companion checks its token at once", null, tagsOfRule);
#line 46
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 47
      await testRunner.GivenAsync("RaidManager answers with the code \"K7M-4QX\" valid for 10 minutes and a polling in" +
                        "terval of 5 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 48
      await testRunner.AndAsync("the companion shows the code", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
      await testRunner.WhenAsync("the player opens the companion", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
      await testRunner.ThenAsync("RaidManager was asked to check the token 0 times", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CompanionPairingCheckWhileItRunsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CompanionPairingCheckWhileItRunsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
