// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Companion.Client.Tests.Features.Sync
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CompanionSyncScreensFeature : object, global::Xunit.IClassFixture<CompanionSyncScreensFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Sync", "Companion sync screens", "  As a player\r\n  I want to review the folders the companion watches and see where" +
                " my uploads stand\r\n  So that I keep characters out when I choose and fix what st" +
                "ops them from syncing", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CompanionSyncScreens.feature"
#line hidden
        
        public CompanionSyncScreensFeature(CompanionSyncScreensFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("this computer is paired with \"Bryn\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("the companion found the accounts \"ARTHASACC, JAINAACC, THRALLACC\" and excluded \"A" +
                    "LTACC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Sync/CompanionSyncScreens.feature.ndjson", 24);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Clearing an account waits for Save and sync")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Clearing an account waits for Save and sync")]
        public async global::System.Threading.Tasks.Task ClearingAnAccountWaitsForSaveAndSync()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clearing an account waits for Save and sync", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player reviews the watched folders and excludes an account", null, tagsOfRule);
#line 12
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 13
      await testRunner.GivenAsync("the window shows the watched folders", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 14
      await testRunner.WhenAsync("the player clears \"JAINAACC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
      await testRunner.ThenAsync("the row of \"JAINAACC\" reads \"Excluded · 2 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
      await testRunner.AndAsync("the sync was asked nothing", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
      await testRunner.WhenAsync("the player saves and syncs", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 18
      await testRunner.ThenAsync("the sync was asked to \"exclude JAINAACC-id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 19
      await testRunner.AndAsync("the window shows the \"Syncing\" board", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Clearing a folder excludes it with its accounts")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Clearing a folder excludes it with its accounts")]
        public async global::System.Threading.Tasks.Task ClearingAFolderExcludesItWithItsAccounts()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Clearing a folder excludes it with its accounts", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player reviews the watched folders and excludes an account", null, tagsOfRule);
#line 21
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 22
      await testRunner.GivenAsync("the window shows the watched folders", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 23
      await testRunner.WhenAsync("the player clears the folder \"D:\\WoW\\Warmane\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 24
      await testRunner.ThenAsync("the row of \"THRALLACC\" reads \"Excluded · 1 character\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 25
      await testRunner.AndAsync("the row of \"THRALLACC\" can\'t be changed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
      await testRunner.WhenAsync("the player saves and syncs", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
      await testRunner.ThenAsync("the sync was asked to \"exclude folder D:\\WoW\\Warmane\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Ticking a folder again ticks every account in it")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Ticking a folder again ticks every account in it")]
        public async global::System.Threading.Tasks.Task TickingAFolderAgainTicksEveryAccountInIt()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ticking a folder again ticks every account in it", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player reviews the watched folders and excludes an account", null, tagsOfRule);
#line 29
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
      await testRunner.GivenAsync("the window shows the watched folders", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
      await testRunner.WhenAsync("the player clears \"JAINAACC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
      await testRunner.AndAsync("the player clears the folder \"C:\\Games\\Warmane\\World of Warcraft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 33
      await testRunner.AndAsync("the player ticks the folder \"C:\\Games\\Warmane\\World of Warcraft\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
      await testRunner.ThenAsync("the row of \"JAINAACC\" reads \"2 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 35
      await testRunner.AndAsync("the row of \"ALTACC\" reads \"4 characters\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
      await testRunner.WhenAsync("the player saves and syncs", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
      await testRunner.ThenAsync("the sync was asked to \"watch ALTACC-id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Ticking an excluded account watches it again")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Ticking an excluded account watches it again")]
        public async global::System.Threading.Tasks.Task TickingAnExcludedAccountWatchesItAgain()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Ticking an excluded account watches it again", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player reviews the watched folders and excludes an account", null, tagsOfRule);
#line 39
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 40
      await testRunner.GivenAsync("the window shows the watched folders", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 41
      await testRunner.WhenAsync("the player ticks \"ALTACC\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 42
      await testRunner.AndAsync("the player saves and syncs", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
      await testRunner.ThenAsync("the sync was asked to \"watch ALTACC-id\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A folder that isn\'t a WoW installation shows a warning")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "A folder that isn\'t a WoW installation shows a warning")]
        public async global::System.Threading.Tasks.Task AFolderThatIsntAWoWInstallationShowsAWarning()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A folder that isn\'t a WoW installation shows a warning", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player reviews the watched folders and excludes an account", null, tagsOfRule);
#line 45
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 46
      await testRunner.GivenAsync("the window shows the watched folders", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 47
      await testRunner.AndAsync("the sync refuses folders without WTF/Account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
      await testRunner.WhenAsync("the player adds the folder \"D:\\Backups\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 49
      await testRunner.ThenAsync("the sync was asked to \"add D:\\Backups\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 50
      await testRunner.AndAsync("the window shows the \"Watched folders\" board with a warning", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A WoW folder added is watched without a warning")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "A WoW folder added is watched without a warning")]
        public async global::System.Threading.Tasks.Task AWoWFolderAddedIsWatchedWithoutAWarning()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A WoW folder added is watched without a warning", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player reviews the watched folders and excludes an account", null, tagsOfRule);
#line 52
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 53
      await testRunner.GivenAsync("the window shows the watched folders", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 54
      await testRunner.WhenAsync("the player adds the folder \"D:\\WoW\\Warmane\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
      await testRunner.ThenAsync("the window shows the \"Watched folders\" board without a warning", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Finding folders again clears the warning")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Finding folders again clears the warning")]
        public async global::System.Threading.Tasks.Task FindingFoldersAgainClearsTheWarning()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Finding folders again clears the warning", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player reviews the watched folders and excludes an account", null, tagsOfRule);
#line 57
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 58
      await testRunner.GivenAsync("the window shows the watched folders", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 59
      await testRunner.AndAsync("the sync refuses folders without WTF/Account", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 60
      await testRunner.AndAsync("the player added the folder \"D:\\Backups\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
      await testRunner.WhenAsync("the player finds folders again", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
      await testRunner.ThenAsync("the sync was asked to \"add D:\\Backups, find folders again\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 63
      await testRunner.AndAsync("the window shows the \"Watched folders\" board without a warning", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Each status has its board")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Each status has its board")]
        [global::Xunit.InlineDataAttribute("uploading", "Syncing", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("paused", "Paused", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("offline", "Offline", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("holding an incomplete file", "Incomplete snapshot", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("holding a refused snapshot", "Refused snapshot", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("holding an unsupported file", "Unsupported addon", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("holding an unreadable file", "Unreadable file", "13", new string[0])]
        public async global::System.Threading.Tasks.Task EachStatusHasItsBoard(string status, string board, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            argumentsOfScenario.Add("board", board);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each status has its board", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The window shows the board the sync\'s status calls for", null, tagsOfRule);
#line 67
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 68
      await testRunner.GivenAsync(string.Format("the sync is \"{0}\"", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 69
      await testRunner.WhenAsync("the player opens the sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 70
      await testRunner.ThenAsync(string.Format("the window shows the \"{0}\" board", board), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A companion that watches nothing opens on the watched folders")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "A companion that watches nothing opens on the watched folders")]
        public async global::System.Threading.Tasks.Task ACompanionThatWatchesNothingOpensOnTheWatchedFolders()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A companion that watches nothing opens on the watched folders", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The window shows the board the sync\'s status calls for", null, tagsOfRule);
#line 82
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 83
      await testRunner.GivenAsync("the sync has found nothing yet", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
      await testRunner.WhenAsync("the player opens the sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 85
      await testRunner.ThenAsync("the window shows the \"Watched folders\" board", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The syncing board shows the stats and the recent activity")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "The syncing board shows the stats and the recent activity")]
        public async global::System.Threading.Tasks.Task TheSyncingBoardShowsTheStatsAndTheRecentActivity()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The syncing board shows the stats and the recent activity", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The status shows pairing, last success, queued uploads and actionable failures", null, tagsOfRule);
#line 89
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 90
      await testRunner.GivenAsync("the sync is \"uploading\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 91
      await testRunner.WhenAsync("the player opens the sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
      await testRunner.ThenAsync("the stats read \"Today, 14:05\", \"2 snapshots\" and \"3 of 4 watched\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 93
      await testRunner.AndAsync("the footer names \"Bryn\" and this computer", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "realm",
                            "state"});
                table1.AddRow(new string[] {
                            "Arthasdk",
                            "Icecrown",
                            "uploading"});
                table1.AddRow(new string[] {
                            "Jainaice",
                            "Lordaeron",
                            "waiting for WoW"});
                table1.AddRow(new string[] {
                            "Thrallsham",
                            "Icecrown",
                            "Uploaded today, 14:05"});
                table1.AddRow(new string[] {
                            "Sylvanash",
                            "Icecrown",
                            "Uploaded yesterday, 14:05"});
#line 94
      await testRunner.AndAsync("the recent activity reads:", ((string)(null)), table1, "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Each problem says what to do and offers a retry")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Each problem says what to do and offers a retry")]
        [global::Xunit.InlineDataAttribute("holding an incomplete file", "Jainaice\'s snapshot is incomplete", "Retry Jainaice", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("holding a refused snapshot", "RaidManager refused Jainaice\'s snapshot", "Retry Jainaice", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("holding an unsupported file", "This addon version isn\'t supported", "Retry", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("holding an unreadable file", "This file isn\'t RaidManager\'s", "Retry", "19", new string[0])]
        public async global::System.Threading.Tasks.Task EachProblemSaysWhatToDoAndOffersARetry(string status, string title, string retry, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("status", status);
            argumentsOfScenario.Add("title", title);
            argumentsOfScenario.Add("retry", retry);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each problem says what to do and offers a retry", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The status shows pairing, last success, queued uploads and actionable failures", null, tagsOfRule);
#line 101
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
      await testRunner.GivenAsync(string.Format("the sync is \"{0}\"", status), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
      await testRunner.WhenAsync("the player opens the sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 104
      await testRunner.ThenAsync(string.Format("the notice reads \"{0}\"", title), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 105
      await testRunner.AndAsync(string.Format("the retry button reads \"{0}\"", retry), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 106
      await testRunner.WhenAsync("the player retries", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 107
      await testRunner.ThenAsync("the sync was asked to \"read again\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Pausing and resuming")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Pausing and resuming")]
        public async global::System.Threading.Tasks.Task PausingAndResuming()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pausing and resuming", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player pauses, resumes and retries uploads", null, tagsOfRule);
#line 118
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 119
      await testRunner.GivenAsync("the sync is \"uploading\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 120
      await testRunner.AndAsync("the player opened the sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 121
      await testRunner.WhenAsync("the player pauses sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 122
      await testRunner.AndAsync("the sync becomes paused", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
      await testRunner.AndAsync("the player resumes sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
      await testRunner.ThenAsync("the sync was asked to \"pause, resume\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Retrying at once while offline")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion sync screens")]
        [global::Xunit.TraitAttribute("Description", "Retrying at once while offline")]
        public async global::System.Threading.Tasks.Task RetryingAtOnceWhileOffline()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retrying at once while offline", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player pauses, resumes and retries uploads", null, tagsOfRule);
#line 126
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 127
      await testRunner.GivenAsync("the sync is \"offline\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 128
      await testRunner.AndAsync("the player opened the sync", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 129
      await testRunner.WhenAsync("the player retries now", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 130
      await testRunner.ThenAsync("the sync was asked to \"retry now\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CompanionSyncScreensFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CompanionSyncScreensFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
