// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Companion.Client.Tests.Features.Sync
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CompanionSnapshotUploadFeature : object, global::Xunit.IClassFixture<CompanionSnapshotUploadFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Sync", "Companion snapshot upload", "  As a player\r\n  I want waiting snapshots to upload on their own and retry until " +
                "RaidManager has them\r\n  So that no character snapshot is lost while I\'m offline", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CompanionSnapshotUpload.feature"
#line hidden
        
        public CompanionSnapshotUploadFeature(CompanionSnapshotUploadFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("this computer is paired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Sync/CompanionSnapshotUpload.feature.ndjson", 24);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="An accepted snapshot leaves the queue")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "An accepted snapshot leaves the queue")]
        [global::Xunit.InlineDataAttribute("Imported", "0", new string[0])]
        [global::Xunit.InlineDataAttribute("AlreadyCurrent", "1", new string[0])]
        public async global::System.Threading.Tasks.Task AnAcceptedSnapshotLeavesTheQueue(string answer, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("answer", answer);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An accepted snapshot leaves the queue", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A snapshot RaidManager accepts leaves the queue", null, tagsOfRule);
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
      await testRunner.AndAsync(string.Format("RaidManager answers uploads with \"{0}\"", answer), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
      await testRunner.ThenAsync("0 snapshots are waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
      await testRunner.AndAsync("the connection is \"Online\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 17
      await testRunner.AndAsync("the last success is recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Waiting snapshots upload oldest first")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "Waiting snapshots upload oldest first")]
        public async global::System.Threading.Tasks.Task WaitingSnapshotsUploadOldestFirst()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Waiting snapshots upload oldest first", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A snapshot RaidManager accepts leaves the queue", null, tagsOfRule);
#line 24
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
      await testRunner.AndAsync("a snapshot of \"Sylvanash\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
      await testRunner.ThenAsync("RaidManager received \"Arthasdk, Sylvanash\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A refused snapshot leaves the queue as a refusal")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "A refused snapshot leaves the queue as a refusal")]
        public async global::System.Threading.Tasks.Task ARefusedSnapshotLeavesTheQueueAsARefusal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A refused snapshot leaves the queue as a refusal", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A snapshot RaidManager refuses is dropped and shown", null, tagsOfRule);
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
      await testRunner.AndAsync("a snapshot of \"Sylvanash\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 35
      await testRunner.AndAsync("RaidManager refuses \"Arthasdk\" with \"Character.Snapshot.IdentityUnavailable\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 36
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 37
      await testRunner.ThenAsync("0 snapshots are waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 38
      await testRunner.AndAsync("the refusals are \"Arthasdk: Character.Snapshot.IdentityUnavailable\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A later acceptance clears the character\'s refusal")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "A later acceptance clears the character\'s refusal")]
        public async global::System.Threading.Tasks.Task ALaterAcceptanceClearsTheCharactersRefusal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A later acceptance clears the character\'s refusal", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A snapshot RaidManager refuses is dropped and shown", null, tagsOfRule);
#line 40
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 41
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 42
      await testRunner.AndAsync("RaidManager refuses \"Arthasdk\" with \"Character.Snapshot.IdentityUnavailable\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 43
      await testRunner.AndAsync("the companion has uploaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 44
      await testRunner.AndAsync("RaidManager accepts \"Arthasdk\" again", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 45
      await testRunner.AndAsync("a newer snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
      await testRunner.ThenAsync("the refusals are \"none\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An unreachable RaidManager keeps the snapshot waiting")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "An unreachable RaidManager keeps the snapshot waiting")]
        public async global::System.Threading.Tasks.Task AnUnreachableRaidManagerKeepsTheSnapshotWaiting()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unreachable RaidManager keeps the snapshot waiting", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload that can\'t reach RaidManager retries with growing waits", null, tagsOfRule);
#line 51
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 52
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
      await testRunner.AndAsync("RaidManager can\'t be reached", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 55
      await testRunner.ThenAsync("1 snapshots are waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 56
      await testRunner.AndAsync("the connection is \"Offline\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Each failure in a row waits longer up to five minutes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "Each failure in a row waits longer up to five minutes")]
        [global::Xunit.InlineDataAttribute("1", "5", "6", "6", new string[0])]
        [global::Xunit.InlineDataAttribute("2", "10", "12", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("3", "20", "24", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("7", "300", "360", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("10", "300", "360", "10", new string[0])]
        public async global::System.Threading.Tasks.Task EachFailureInARowWaitsLongerUpToFiveMinutes(string failures, string least, string most, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("failures", failures);
            argumentsOfScenario.Add("least", least);
            argumentsOfScenario.Add("most", most);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Each failure in a row waits longer up to five minutes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload that can\'t reach RaidManager retries with growing waits", null, tagsOfRule);
#line 58
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 60
      await testRunner.AndAsync("RaidManager can\'t be reached", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 61
      await testRunner.WhenAsync(string.Format("the companion fails to upload {0} times in a row", failures), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 62
      await testRunner.ThenAsync(string.Format("the next upload waits at least {0} seconds", least), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 63
      await testRunner.AndAsync(string.Format("the next upload waits at most {0} seconds", most), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="The snapshot uploads once the wait has passed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "The snapshot uploads once the wait has passed")]
        [global::Xunit.InlineDataAttribute("4", "1", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("7", "0", "12", new string[0])]
        public async global::System.Threading.Tasks.Task TheSnapshotUploadsOnceTheWaitHasPassed(string seconds, string waiting, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("seconds", seconds);
            argumentsOfScenario.Add("waiting", waiting);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The snapshot uploads once the wait has passed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload that can\'t reach RaidManager retries with growing waits", null, tagsOfRule);
#line 73
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 74
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 75
      await testRunner.AndAsync("RaidManager can\'t be reached", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 76
      await testRunner.AndAsync("the companion has uploaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
      await testRunner.AndAsync("RaidManager is reachable again", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 78
      await testRunner.WhenAsync(string.Format("the companion uploads {0} seconds later", seconds), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
      await testRunner.ThenAsync(string.Format("{0} snapshots are waiting", waiting), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Retrying now uploads at once")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "Retrying now uploads at once")]
        public async global::System.Threading.Tasks.Task RetryingNowUploadsAtOnce()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Retrying now uploads at once", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload that can\'t reach RaidManager retries with growing waits", null, tagsOfRule);
#line 86
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 87
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 88
      await testRunner.AndAsync("RaidManager can\'t be reached", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 89
      await testRunner.AndAsync("the companion has uploaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 90
      await testRunner.AndAsync("RaidManager is reachable again", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 91
      await testRunner.WhenAsync("the player retries now", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 92
      await testRunner.ThenAsync("0 snapshots are waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A slow-down waits as long as RaidManager asks")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "A slow-down waits as long as RaidManager asks")]
        [global::Xunit.InlineDataAttribute("30 seconds", "29", "1", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("30 seconds", "30", "0", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("nothing", "59", "1", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("nothing", "60", "0", "17", new string[0])]
        public async global::System.Threading.Tasks.Task ASlow_DownWaitsAsLongAsRaidManagerAsks(string asked, string seconds, string waiting, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("asked", asked);
            argumentsOfScenario.Add("seconds", seconds);
            argumentsOfScenario.Add("waiting", waiting);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A slow-down waits as long as RaidManager asks", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("RaidManager\'s request to slow down is obeyed", null, tagsOfRule);
#line 96
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 97
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 98
      await testRunner.AndAsync(string.Format("RaidManager asks to slow down for \"{0}\"", asked), ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
      await testRunner.AndAsync("the companion has uploaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 100
      await testRunner.AndAsync("RaidManager is reachable again", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 101
      await testRunner.WhenAsync(string.Format("the companion uploads {0} seconds later", seconds), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 102
      await testRunner.ThenAsync(string.Format("{0} snapshots are waiting", waiting), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A refused device token stops uploads")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "A refused device token stops uploads")]
        public async global::System.Threading.Tasks.Task ARefusedDeviceTokenStopsUploads()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A refused device token stops uploads", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Uploads need a device token RaidManager accepts", null, tagsOfRule);
#line 113
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 114
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 115
      await testRunner.AndAsync("RaidManager refuses the device token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 116
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 117
      await testRunner.ThenAsync("1 snapshots are waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 118
      await testRunner.AndAsync("the connection is \"NeedsPairing\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The refused device token isn\'t sent again")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "The refused device token isn\'t sent again")]
        public async global::System.Threading.Tasks.Task TheRefusedDeviceTokenIsntSentAgain()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The refused device token isn\'t sent again", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Uploads need a device token RaidManager accepts", null, tagsOfRule);
#line 120
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 121
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 122
      await testRunner.AndAsync("RaidManager refuses the device token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 123
      await testRunner.AndAsync("the companion has uploaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 124
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 125
      await testRunner.ThenAsync("RaidManager received \"Arthasdk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Pairing again resumes uploads")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "Pairing again resumes uploads")]
        public async global::System.Threading.Tasks.Task PairingAgainResumesUploads()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "20";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Pairing again resumes uploads", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Uploads need a device token RaidManager accepts", null, tagsOfRule);
#line 127
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 128
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
      await testRunner.AndAsync("RaidManager refuses the device token", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
      await testRunner.AndAsync("the companion has uploaded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 131
      await testRunner.AndAsync("this computer is paired again", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 132
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 133
      await testRunner.ThenAsync("0 snapshots are waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A computer that isn\'t paired uploads nothing")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion snapshot upload")]
        [global::Xunit.TraitAttribute("Description", "A computer that isn\'t paired uploads nothing")]
        public async global::System.Threading.Tasks.Task AComputerThatIsntPairedUploadsNothing()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "21";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A computer that isn\'t paired uploads nothing", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Uploads need a device token RaidManager accepts", null, tagsOfRule);
#line 135
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 136
      await testRunner.GivenAsync("a snapshot of \"Arthasdk\" is waiting", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 137
      await testRunner.AndAsync("the pairing is removed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 138
      await testRunner.WhenAsync("the companion uploads", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 139
      await testRunner.ThenAsync("RaidManager received \"none\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 140
      await testRunner.AndAsync("the connection is \"NotPaired\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CompanionSnapshotUploadFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CompanionSnapshotUploadFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
