<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <PackageId>RaidManager.ViewModels.Tests</PackageId>
    <Version>1.0.0</Version>
    <PackageTags>tests;core;raid-management</PackageTags>
    <Description>Tests for RaidManager UI view models.</Description>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../../../src/Containers/UI/Core/RaidManager.ViewModels/RaidManager.ViewModels.csproj" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Microsoft.Extensions.TimeProvider.Testing" />
    <PackageReference Include="xunit" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.runner.visualstudio"><PrivateAssets>all</PrivateAssets></PackageReference>
    <PackageReference Include="coverlet.collector"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
</Project>
