<Project Sdk="Microsoft.NET.Sdk.Web">
  <ItemGroup>
    <ProjectReference Include="../../../Core/WarmaneRaidManager.Application/WarmaneRaidManager.Application.csproj" />
    <ProjectReference Include="../../../Infrastructure/WarmaneRaidManager.Infrastructure/WarmaneRaidManager.Infrastructure.csproj" />
    <ProjectReference Include="../../../Infrastructure/WarmaneRaidManager.Persistence.EntityFrameworkCore/WarmaneRaidManager.Persistence.EntityFrameworkCore.csproj" />
    <ProjectReference Include="../../Aspire/Defaults/WarmaneRaidManager.ServiceDefaults/WarmaneRaidManager.ServiceDefaults.csproj" />
    <PackageReference Include="Pivot.Framework.Containers.API" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Pivot.Framework.Tools.DependencyInjection" />
  </ItemGroup>
</Project>
