// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Application.Tests.Features.Characters.Commands
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CharacterSnapshotImportFeature : object, global::Xunit.IClassFixture<CharacterSnapshotImportFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Characters/Commands", "Character snapshot import", "  As a player\r\n  I want my companion\'s uploads to reach my characters\r\n  So that " +
                "new characters wait for my review and known ones stay current", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CharacterSnapshotImport.feature"
#line hidden
        
        public CharacterSnapshotImportFeature(CharacterSnapshotImportFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("the companion of \"Bryn\" is paired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Characters/Commands/CharacterSnapshotImport.feature.ndjson", 32);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A snapshot of an unknown character imports it")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "A snapshot of an unknown character imports it")]
        public async global::System.Threading.Tasks.Task ASnapshotOfAnUnknownCharacterImportsIt()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A snapshot of an unknown character imports it", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A new character is imported with a pending claim for the companion\'s player", null, tagsOfRule);
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
      await testRunner.WhenAsync("the companion uploads a snapshot of \"Arthasdk\" captured 1 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
      await testRunner.ThenAsync("the upload is \"Imported\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
      await testRunner.AndAsync("\"Arthasdk\" is imported with a \"Pending\" claim for \"Bryn\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 15
      await testRunner.AndAsync("the companion\'s last upload is recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 16
      await testRunner.AndAsync("the import is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An unknown character without its identity is refused")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "An unknown character without its identity is refused")]
        public async global::System.Threading.Tasks.Task AnUnknownCharacterWithoutItsIdentityIsRefused()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unknown character without its identity is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A new character is imported with a pending claim for the companion\'s player", null, tagsOfRule);
#line 18
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
      await testRunner.WhenAsync("the companion uploads a snapshot of \"Arthasdk\" without its identity", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
      await testRunner.ThenAsync("the upload fails with \"Character.Snapshot.IdentityUnavailable\" as ValidationError" +
                        "", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 21
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A character another player owns keeps its owner")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "A character another player owns keeps its owner")]
        public async global::System.Threading.Tasks.Task ACharacterAnotherPlayerOwnsKeepsItsOwner()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A character another player owns keeps its owner", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A known character keeps its owner and changes only for a newer snapshot", null, tagsOfRule);
#line 25
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 26
      await testRunner.GivenAsync("\"Alice\" owns \"Arthasdk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 27
      await testRunner.WhenAsync("the companion uploads a snapshot of \"Arthasdk\" captured 1 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
      await testRunner.ThenAsync("the upload is \"Imported\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 29
      await testRunner.AndAsync("\"Alice\" owns \"Arthasdk\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 30
      await testRunner.AndAsync("\"Arthasdk\" has a \"Conflict\" claim for \"Bryn\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A repeated snapshot is already current")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "A repeated snapshot is already current")]
        public async global::System.Threading.Tasks.Task ARepeatedSnapshotIsAlreadyCurrent()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A repeated snapshot is already current", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A known character keeps its owner and changes only for a newer snapshot", null, tagsOfRule);
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
      await testRunner.GivenAsync("the companion uploaded a snapshot of \"Arthasdk\" captured 1 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
      await testRunner.WhenAsync("the companion uploads the same snapshot again", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
      await testRunner.ThenAsync("the upload is \"AlreadyCurrent\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
      await testRunner.AndAsync("the companion\'s last upload is recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 37
      await testRunner.AndAsync("the import is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A companion that no longer exists is not found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "A companion that no longer exists is not found")]
        public async global::System.Threading.Tasks.Task ACompanionThatNoLongerExistsIsNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A companion that no longer exists is not found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload needs a paired companion and a commit", null, tagsOfRule);
#line 41
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 42
      await testRunner.GivenAsync("the companion no longer exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 43
      await testRunner.WhenAsync("the companion uploads a snapshot of \"Arthasdk\" captured 1 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 44
      await testRunner.ThenAsync("the upload fails with \"Companion.NotFound\" as NotFound", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 45
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A failed commit is returned")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "A failed commit is returned")]
        public async global::System.Threading.Tasks.Task AFailedCommitIsReturned()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A failed commit is returned", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload needs a paired companion and a commit", null, tagsOfRule);
#line 47
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 48
      await testRunner.GivenAsync("the commit will fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 49
      await testRunner.WhenAsync("the companion uploads a snapshot of \"Arthasdk\" captured 1 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
      await testRunner.ThenAsync("the upload fails with \"Commit.Failed\" as ValidationError", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A snapshot that follows the contract passes validation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "A snapshot that follows the contract passes validation")]
        public async global::System.Threading.Tasks.Task ASnapshotThatFollowsTheContractPassesValidation()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A snapshot that follows the contract passes validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A snapshot that breaks the addon contract is refused before the handler runs", null, tagsOfRule);
#line 54
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 55
      await testRunner.WhenAsync("a snapshot without changes is validated", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
      await testRunner.ThenAsync("the validation passes", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A snapshot that breaks the contract fails validation")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character snapshot import")]
        [global::Xunit.TraitAttribute("Description", "A snapshot that breaks the contract fails validation")]
        [global::Xunit.InlineDataAttribute("schema version 2", "SchemaVersion", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("no companion", "CompanionId", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("no character", "Character", "9", new string[0])]
        [global::Xunit.InlineDataAttribute("realm Northrend", "Character.Realm", "10", new string[0])]
        [global::Xunit.InlineDataAttribute("realm 1", "Character.Realm", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("name with a digit", "Character.Name", "12", new string[0])]
        [global::Xunit.InlineDataAttribute("capture tomorrow", "Character.CapturedAt", "13", new string[0])]
        [global::Xunit.InlineDataAttribute("unknown section status", "Character.Guild", "14", new string[0])]
        [global::Xunit.InlineDataAttribute("observed guild without time", "Character.Guild", "15", new string[0])]
        [global::Xunit.InlineDataAttribute("unknown class", "Character.Identity.Class", "16", new string[0])]
        [global::Xunit.InlineDataAttribute("unknown race", "Character.Identity.Race", "17", new string[0])]
        [global::Xunit.InlineDataAttribute("unknown faction", "Character.Identity.Faction", "18", new string[0])]
        [global::Xunit.InlineDataAttribute("level 81", "Character.Identity.Level", "19", new string[0])]
        [global::Xunit.InlineDataAttribute("guild without a name", "Character.Guild.Name", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("profession above its maximum", "Character.Professions.Items[0].MaxRank", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("slot 20", "Character.Equipped.Slots[0].Slot", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("slot listed twice", "Character.Equipped.Slots", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("item without an id", "Character.Equipped.Slots[0].ItemId", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("third talent group", "Character.Talents.ActiveGroup", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("two talent trees", "Character.Talents.Groups[0].Tabs", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("ranks with a letter", "Character.Talents.Groups[0].Tabs[0].Ranks", "27", new string[0])]
        [global::Xunit.InlineDataAttribute("scan without completeness", "Character.Lockouts.Complete", "28", new string[0])]
        [global::Xunit.InlineDataAttribute("reset in 61 days", "Character.Lockouts.Items[0].ResetSeconds", "29", new string[0])]
        public async global::System.Threading.Tasks.Task ASnapshotThatBreaksTheContractFailsValidation(string change, string property, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("change", change);
            argumentsOfScenario.Add("property", property);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A snapshot that breaks the contract fails validation", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A snapshot that breaks the addon contract is refused before the handler runs", null, tagsOfRule);
#line 58
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.WhenAsync(string.Format("a snapshot with \"{0}\" is validated", change), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
      await testRunner.ThenAsync(string.Format("the validation fails on \"{0}\"", property), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CharacterSnapshotImportFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CharacterSnapshotImportFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
