<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAspireHost>true</IsAspireHost>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../../API/WarmaneRaidManager.ApiService/WarmaneRaidManager.ApiService.csproj" />
    <ProjectReference Include="../../../UI/Hosting/WarmaneRaidManager.Web/WarmaneRaidManager.Web.csproj" />
    <ProjectReference Include="../../../Jobs/WarmaneRaidManager.DiscordBot/WarmaneRaidManager.DiscordBot.csproj" />
    <PackageReference Include="Aspire.Hosting.AppHost" />
  </ItemGroup>
</Project>
