// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Application.Tests.Features.Companions.Commands
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CompanionPairingUseCasesFeature : object, global::Xunit.IClassFixture<CompanionPairingUseCasesFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Companions/Commands", "Companion pairing use cases", "  As a player\r\n  I want my companion paired, checked and revoked through one flow" +
                "\r\n  So that only the computers I confirm upload for me", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CompanionPairingUseCases.feature"
#line hidden
        
        public CompanionPairingUseCasesFeature(CompanionPairingUseCasesFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("\"Bryn\" is a registered player", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Companions/Commands/CompanionPairingUseCases.feature.ndjson", 30);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A code in use is replaced by a free one")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A code in use is replaced by a free one")]
        public async global::System.Threading.Tasks.Task ACodeInUseIsReplacedByAFreeOne()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A code in use is replaced by a free one", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Starting a pairing draws a code no live pairing shows", null, tagsOfRule);
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
      await testRunner.GivenAsync("the next codes drawn are \"K7M4QX\" then \"ABC234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 13
      await testRunner.AndAsync("the code \"K7M4QX\" is in use", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 14
      await testRunner.WhenAsync("a companion starts pairing as \"BRYN-DESKTOP\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 15
      await testRunner.ThenAsync("the pairing shows \"ABC-234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 16
      await testRunner.AndAsync("the pairing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A generator that only draws codes in use is a fault")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A generator that only draws codes in use is a fault")]
        public async global::System.Threading.Tasks.Task AGeneratorThatOnlyDrawsCodesInUseIsAFault()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A generator that only draws codes in use is a fault", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Starting a pairing draws a code no live pairing shows", null, tagsOfRule);
#line 18
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
      await testRunner.GivenAsync("the next codes drawn are \"K7M4QX\" then \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
      await testRunner.AndAsync("the code \"K7M4QX\" is in use", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
      await testRunner.WhenAsync("a companion starts pairing as \"BRYN-DESKTOP\" expecting a fault", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
      await testRunner.ThenAsync("the start fails with a fault", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A failed commit is returned from the start")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A failed commit is returned from the start")]
        public async global::System.Threading.Tasks.Task AFailedCommitIsReturnedFromTheStart()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A failed commit is returned from the start", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Starting a pairing draws a code no live pairing shows", null, tagsOfRule);
#line 24
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
      await testRunner.GivenAsync("the next codes drawn are \"K7M4QX\" then \"ABC234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
      await testRunner.AndAsync("the commit will fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
      await testRunner.WhenAsync("a companion starts pairing as \"BRYN-DESKTOP\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
      await testRunner.ThenAsync("the use case fails with \"Commit.Failed\" as ValidationError", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An unknown player can\'t confirm")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "An unknown player can\'t confirm")]
        public async global::System.Threading.Tasks.Task AnUnknownPlayerCantConfirm()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unknown player can\'t confirm", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Confirming needs a known player and a pairing that shows the code", null, tagsOfRule);
#line 32
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 33
      await testRunner.GivenAsync("a companion waits with the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 34
      await testRunner.WhenAsync("\"Mallory\" confirms the code \"K7M-4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 35
      await testRunner.ThenAsync("the use case fails with \"User.NotFound\" as NotFound", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 36
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An unknown code isn\'t found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "An unknown code isn\'t found")]
        public async global::System.Threading.Tasks.Task AnUnknownCodeIsntFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unknown code isn\'t found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Confirming needs a known player and a pairing that shows the code", null, tagsOfRule);
#line 38
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 39
      await testRunner.WhenAsync("\"Bryn\" confirms the code \"ABC-234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
      await testRunner.ThenAsync("the use case fails with \"CompanionPairing.NotFound\" as NotFound", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A confirmed code is committed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A confirmed code is committed")]
        public async global::System.Threading.Tasks.Task AConfirmedCodeIsCommitted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A confirmed code is committed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Confirming needs a known player and a pairing that shows the code", null, tagsOfRule);
#line 43
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 44
      await testRunner.GivenAsync("a companion waits with the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
      await testRunner.WhenAsync("\"Bryn\" confirms the code \"k7m-4qx\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 46
      await testRunner.ThenAsync("the use case succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 47
      await testRunner.AndAsync("the pairing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A code confirmed twice isn\'t committed again")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A code confirmed twice isn\'t committed again")]
        public async global::System.Threading.Tasks.Task ACodeConfirmedTwiceIsntCommittedAgain()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A code confirmed twice isn\'t committed again", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Confirming needs a known player and a pairing that shows the code", null, tagsOfRule);
#line 49
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 50
      await testRunner.GivenAsync("a companion waits with the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 51
      await testRunner.AndAsync("\"Bryn\" confirmed the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 52
      await testRunner.WhenAsync("\"Bryn\" confirms the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 53
      await testRunner.ThenAsync("the use case fails with \"CompanionPairing.AlreadyConfirmed\" as Conflict", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 54
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An unknown device code is invalid")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "An unknown device code is invalid")]
        public async global::System.Threading.Tasks.Task AnUnknownDeviceCodeIsInvalid()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An unknown device code is invalid", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The companion collects its token once its player confirmed the code", null, tagsOfRule);
#line 58
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 59
      await testRunner.WhenAsync("the companion collects its token with an unknown device code", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 60
      await testRunner.ThenAsync("the use case fails with \"CompanionPairing.Invalid\" as ValidationError", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 61
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A pending pairing isn\'t committed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A pending pairing isn\'t committed")]
        public async global::System.Threading.Tasks.Task APendingPairingIsntCommitted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A pending pairing isn\'t committed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The companion collects its token once its player confirmed the code", null, tagsOfRule);
#line 63
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 64
      await testRunner.GivenAsync("a companion waits with the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 65
      await testRunner.WhenAsync("the companion collects its token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
      await testRunner.ThenAsync("the use case fails with \"CompanionPairing.Pending\" as ValidationError", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A confirmed pairing gives the token with the player\'s name")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A confirmed pairing gives the token with the player\'s name")]
        public async global::System.Threading.Tasks.Task AConfirmedPairingGivesTheTokenWithThePlayersName()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A confirmed pairing gives the token with the player\'s name", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The companion collects its token once its player confirmed the code", null, tagsOfRule);
#line 69
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 70
      await testRunner.GivenAsync("a companion waits with the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 71
      await testRunner.AndAsync("\"Bryn\" confirmed the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 72
      await testRunner.WhenAsync("the companion collects its token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 73
      await testRunner.ThenAsync("the companion receives a token for \"Bryn\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 74
      await testRunner.AndAsync("the companion is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A player removed after confirming isn\'t paired")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A player removed after confirming isn\'t paired")]
        public async global::System.Threading.Tasks.Task APlayerRemovedAfterConfirmingIsntPaired()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A player removed after confirming isn\'t paired", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The companion collects its token once its player confirmed the code", null, tagsOfRule);
#line 76
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 77
      await testRunner.GivenAsync("a companion waits with the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 78
      await testRunner.AndAsync("\"Bryn\" confirmed the code \"K7M4QX\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 79
      await testRunner.AndAsync("\"Bryn\" no longer exists", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
      await testRunner.WhenAsync("the companion collects its token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
      await testRunner.ThenAsync("the use case fails with \"User.NotFound\" as NotFound", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A missing or unknown token is refused")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A missing or unknown token is refused")]
        [global::Xunit.InlineDataAttribute("", "11", new string[0])]
        [global::Xunit.InlineDataAttribute("unknown-token", "12", new string[0])]
        public async global::System.Threading.Tasks.Task AMissingOrUnknownTokenIsRefused(string token, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("token", token);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A missing or unknown token is refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Every companion request is checked by its token", null, tagsOfRule);
#line 86
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 87
      await testRunner.WhenAsync(string.Format("a companion calls with the token \"{0}\"", token), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 88
      await testRunner.ThenAsync("the use case fails with \"Companion.TokenUnknown\" as AuthenticationRequired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A paired companion is admitted and its first use in an hour is committed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A paired companion is admitted and its first use in an hour is committed")]
        public async global::System.Threading.Tasks.Task APairedCompanionIsAdmittedAndItsFirstUseInAnHourIsCommitted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "13";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A paired companion is admitted and its first use in an hour is committed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Every companion request is checked by its token", null, tagsOfRule);
#line 95
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 96
      await testRunner.GivenAsync("a companion paired for \"Bryn\" 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 97
      await testRunner.WhenAsync("the companion calls with its token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
      await testRunner.ThenAsync("the companion is admitted for \"Bryn\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 99
      await testRunner.AndAsync("the companion is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A failed commit of last use is returned")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A failed commit of last use is returned")]
        public async global::System.Threading.Tasks.Task AFailedCommitOfLastUseIsReturned()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "14";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A failed commit of last use is returned", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Every companion request is checked by its token", null, tagsOfRule);
#line 101
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 102
      await testRunner.GivenAsync("a companion paired for \"Bryn\" 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 103
      await testRunner.AndAsync("the commit will fail", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 104
      await testRunner.WhenAsync("the companion calls with its token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 105
      await testRunner.ThenAsync("the use case fails with \"Commit.Failed\" as ValidationError", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A revoked companion is refused without a commit")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "A revoked companion is refused without a commit")]
        public async global::System.Threading.Tasks.Task ARevokedCompanionIsRefusedWithoutACommit()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "15";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A revoked companion is refused without a commit", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Every companion request is checked by its token", null, tagsOfRule);
#line 107
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 108
      await testRunner.GivenAsync("a companion paired for \"Bryn\" 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 109
      await testRunner.AndAsync("\"Bryn\" revoked the companion", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 110
      await testRunner.WhenAsync("the companion calls with its token", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 111
      await testRunner.ThenAsync("the use case fails with \"Companion.Revoked\" as AuthenticationRequired", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 112
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="The list shows each companion\'s status")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "The list shows each companion\'s status")]
        public async global::System.Threading.Tasks.Task TheListShowsEachCompanionsStatus()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "16";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("The list shows each companion\'s status", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player lists and revokes their companions", null, tagsOfRule);
#line 116
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 117
      await testRunner.GivenAsync("a companion paired for \"Bryn\" 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 118
      await testRunner.AndAsync("\"Bryn\" revoked the companion", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 119
      await testRunner.WhenAsync("\"Bryn\" lists their companions", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 120
      await testRunner.ThenAsync("the list shows one companion with the status Revoked", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Revoking an unknown companion isn\'t found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "Revoking an unknown companion isn\'t found")]
        public async global::System.Threading.Tasks.Task RevokingAnUnknownCompanionIsntFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "17";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Revoking an unknown companion isn\'t found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player lists and revokes their companions", null, tagsOfRule);
#line 122
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 123
      await testRunner.WhenAsync("\"Bryn\" revokes an unknown companion", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 124
      await testRunner.ThenAsync("the use case fails with \"Companion.NotFound\" as NotFound", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 125
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Revoking another player\'s companion isn\'t found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "Revoking another player\'s companion isn\'t found")]
        public async global::System.Threading.Tasks.Task RevokingAnotherPlayersCompanionIsntFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "18";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Revoking another player\'s companion isn\'t found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player lists and revokes their companions", null, tagsOfRule);
#line 127
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 128
      await testRunner.GivenAsync("a companion paired for \"Bryn\" 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 129
      await testRunner.AndAsync("\"Mallory\" is a registered player", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 130
      await testRunner.WhenAsync("\"Mallory\" revokes the companion", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 131
      await testRunner.ThenAsync("the use case fails with \"Companion.NotFound\" as NotFound", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 132
      await testRunner.AndAsync("nothing is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Revoking a companion is committed")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "Revoking a companion is committed")]
        public async global::System.Threading.Tasks.Task RevokingACompanionIsCommitted()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "19";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Revoking a companion is committed", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("The player lists and revokes their companions", null, tagsOfRule);
#line 134
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 135
      await testRunner.GivenAsync("a companion paired for \"Bryn\" 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 136
      await testRunner.WhenAsync("\"Bryn\" revokes the companion", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 137
      await testRunner.ThenAsync("the use case succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 138
      await testRunner.AndAsync("the companion is committed", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="Malformed requests are refused")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Companion pairing use cases")]
        [global::Xunit.TraitAttribute("Description", "Malformed requests are refused")]
        [global::Xunit.InlineDataAttribute("confirmation without a player", "UserId", "20", new string[0])]
        [global::Xunit.InlineDataAttribute("confirmation with a bad code", "PairingCode", "21", new string[0])]
        [global::Xunit.InlineDataAttribute("lookup with a bad code", "PairingCode", "22", new string[0])]
        [global::Xunit.InlineDataAttribute("collection without a code", "DeviceCode", "23", new string[0])]
        [global::Xunit.InlineDataAttribute("start with a long label", "ComputerLabel", "24", new string[0])]
        [global::Xunit.InlineDataAttribute("list without a player", "UserId", "25", new string[0])]
        [global::Xunit.InlineDataAttribute("revocation without a player", "UserId", "26", new string[0])]
        [global::Xunit.InlineDataAttribute("revocation without a companion", "CompanionId", "27", new string[0])]
        public async global::System.Threading.Tasks.Task MalformedRequestsAreRefused(string request, string property, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("request", request);
            argumentsOfScenario.Add("property", property);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Malformed requests are refused", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Requests are validated before their handler runs", null, tagsOfRule);
#line 142
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 143
      await testRunner.WhenAsync(string.Format("the {0} is validated", request), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 144
      await testRunner.ThenAsync(string.Format("the validation fails on \"{0}\"", property), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CompanionPairingUseCasesFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CompanionPairingUseCasesFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
