// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Domain.Tests.Features.Characters.Aggregates
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CharacterProfessionsFeature : object, global::Xunit.IClassFixture<CharacterProfessionsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Characters/Aggregates", "Character professions", "  As a player\r\n  I want my profile to show the professions the addon read\r\n  So t" +
                "hat officers and I see trustworthy skill facts before signups", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CharacterProfessions.feature"
#line hidden
        
        public CharacterProfessionsFeature(CharacterProfessionsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
            global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                        "name",
                        "rank",
                        "maxRank"});
            table3.AddRow(new string[] {
                        "Blacksmithing",
                        "450",
                        "450"});
            table3.AddRow(new string[] {
                        "Mining",
                        "450",
                        "450"});
#line 7
    await testRunner.GivenAsync("a character whose professions were read 2 hours ago", ((string)(null)), table3, "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Characters/Aggregates/CharacterProfessions.feature.ndjson", 9);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A newer read replaces the professions")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character professions")]
        [global::Xunit.TraitAttribute("Description", "A newer read replaces the professions")]
        public async global::System.Threading.Tasks.Task ANewerReadReplacesTheProfessions()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A newer read replaces the professions", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A complete read replaces the professions, in the game\'s order", null, tagsOfRule);
#line 14
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "rank",
                            "maxRank"});
                table4.AddRow(new string[] {
                            "Jewelcrafting",
                            "440",
                            "450"});
                table4.AddRow(new string[] {
                            "Mining",
                            "450",
                            "450"});
#line 15
      await testRunner.WhenAsync("the professions are read 1 hours ago", ((string)(null)), table4, "When ");
#line hidden
#line 19
      await testRunner.ThenAsync("the read is recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "rank",
                            "maxRank"});
                table5.AddRow(new string[] {
                            "Jewelcrafting",
                            "440",
                            "450"});
                table5.AddRow(new string[] {
                            "Mining",
                            "450",
                            "450"});
#line 20
      await testRunner.AndAsync("the character has these professions", ((string)(null)), table5, "And ");
#line hidden
#line 24
      await testRunner.AndAsync("the professions were last read 1 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 25
      await testRunner.AndAsync("the last addon sync was 1 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A read without professions clears them")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character professions")]
        [global::Xunit.TraitAttribute("Description", "A read without professions clears them")]
        public async global::System.Threading.Tasks.Task AReadWithoutProfessionsClearsThem()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A read without professions clears them", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A complete read replaces the professions, in the game\'s order", null, tagsOfRule);
#line 27
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "rank",
                            "maxRank"});
#line 28
      await testRunner.WhenAsync("the professions are read 1 hours ago", ((string)(null)), table6, "When ");
#line hidden
#line 30
      await testRunner.ThenAsync("the read is recorded", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 31
      await testRunner.AndAsync("the character has no professions", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="An out-of-order read is ignored")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character professions")]
        [global::Xunit.TraitAttribute("Description", "An out-of-order read is ignored")]
        public async global::System.Threading.Tasks.Task AnOut_Of_OrderReadIsIgnored()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An out-of-order read is ignored", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An older read cannot replace newer professions", null, tagsOfRule);
#line 35
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
                global::Reqnroll.Table table7 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "rank",
                            "maxRank"});
                table7.AddRow(new string[] {
                            "Fishing",
                            "75",
                            "150"});
#line 36
      await testRunner.WhenAsync("the professions are read 3 hours ago", ((string)(null)), table7, "When ");
#line hidden
#line 39
      await testRunner.ThenAsync("the read is ignored", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
                global::Reqnroll.Table table8 = new global::Reqnroll.Table(new string[] {
                            "name",
                            "rank",
                            "maxRank"});
                table8.AddRow(new string[] {
                            "Blacksmithing",
                            "450",
                            "450"});
                table8.AddRow(new string[] {
                            "Mining",
                            "450",
                            "450"});
#line 40
      await testRunner.AndAsync("the character has these professions", ((string)(null)), table8, "And ");
#line hidden
#line 44
      await testRunner.AndAsync("the professions were last read 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="An invalid profession is rejected and nothing changes")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character professions")]
        [global::Xunit.TraitAttribute("Description", "An invalid profession is rejected and nothing changes")]
        [global::Xunit.InlineDataAttribute("", "75", "150", "3", new string[0])]
        [global::Xunit.InlineDataAttribute("Fishing", "-1", "150", "4", new string[0])]
        [global::Xunit.InlineDataAttribute("Fishing", "151", "150", "5", new string[0])]
        public async global::System.Threading.Tasks.Task AnInvalidProfessionIsRejectedAndNothingChanges(string name, string rank, string maxRank, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("name", name);
            argumentsOfScenario.Add("rank", rank);
            argumentsOfScenario.Add("maxRank", maxRank);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("An invalid profession is rejected and nothing changes", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A profession needs a name and a skill within its training", null, tagsOfRule);
#line 48
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 49
      await testRunner.WhenAsync(string.Format("the professions are read 1 hours ago with \"{0}\" at {1} of {2}", name, rank, maxRank), ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 50
      await testRunner.ThenAsync("the read fails with a domain error", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 51
      await testRunner.AndAsync("the professions were last read 2 hours ago", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A new character is visible to the community")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character professions")]
        [global::Xunit.TraitAttribute("Description", "A new character is visible to the community")]
        public async global::System.Threading.Tasks.Task ANewCharacterIsVisibleToTheCommunity()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A new character is visible to the community", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A profile is visible to the community until its owner chooses otherwise", null, tagsOfRule);
#line 61
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 62
      await testRunner.ThenAsync("the character\'s visibility is Community", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CharacterProfessionsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CharacterProfessionsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
