// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace RaidManager.Domain.Tests.Features.Characters.Aggregates
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CharacterClaimsFeature : object, global::Xunit.IClassFixture<CharacterClaimsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Characters/Aggregates", "Character claims", "  As a player\r\n  I want to approve the characters my companion discovers\r\n  So th" +
                "at only characters I own become raid signup options", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CharacterClaims.feature"
#line hidden
        
        public CharacterClaimsFeature(CharacterClaimsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("a level 80 character on Icecrown", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Characters/Aggregates/CharacterClaims.feature.ndjson", 15);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Discovery creates a pending claim")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Discovery creates a pending claim")]
        public async global::System.Threading.Tasks.Task DiscoveryCreatesAPendingClaim()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Discovery creates a pending claim", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A discovered character waits for its player\'s decision", null, tagsOfRule);
#line 11
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 12
      await testRunner.WhenAsync("the companion of \"Alice\" uploads the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 13
      await testRunner.ThenAsync("the claim of \"Alice\" is \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 14
      await testRunner.AndAsync("the character has no owner", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Approving a pending claim makes the player the owner")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Approving a pending claim makes the player the owner")]
        public async global::System.Threading.Tasks.Task ApprovingAPendingClaimMakesThePlayerTheOwner()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Approving a pending claim makes the player the owner", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A discovered character waits for its player\'s decision", null, tagsOfRule);
#line 16
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 17
      await testRunner.GivenAsync("the companion of \"Alice\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 18
      await testRunner.WhenAsync("\"Alice\" approves the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 19
      await testRunner.ThenAsync("the claim decision succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 20
      await testRunner.AndAsync("the claim of \"Alice\" is \"Approved\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
      await testRunner.AndAsync("\"Alice\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Approving without a claim is not found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Approving without a claim is not found")]
        public async global::System.Threading.Tasks.Task ApprovingWithoutAClaimIsNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Approving without a claim is not found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A discovered character waits for its player\'s decision", null, tagsOfRule);
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
      await testRunner.WhenAsync("\"Alice\" approves the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
      await testRunner.ThenAsync("the claim decision fails with \"Character.Claim.NotFound\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Uploading again after rejection keeps the claim rejected")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Uploading again after rejection keeps the claim rejected")]
        public async global::System.Threading.Tasks.Task UploadingAgainAfterRejectionKeepsTheClaimRejected()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Uploading again after rejection keeps the claim rejected", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("A rejected claim stays rejected", null, tagsOfRule);
#line 29
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
      await testRunner.GivenAsync("the companion of \"Alice\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
      await testRunner.AndAsync("\"Alice\" rejected the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 32
      await testRunner.WhenAsync("the companion of \"Alice\" uploads the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 33
      await testRunner.ThenAsync("the claim of \"Alice\" is \"Rejected\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 34
      await testRunner.AndAsync("the character has no owner", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Another player\'s discovery of an owned character is a conflict")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Another player\'s discovery of an owned character is a conflict")]
        public async global::System.Threading.Tasks.Task AnotherPlayersDiscoveryOfAnOwnedCharacterIsAConflict()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Another player\'s discovery of an owned character is a conflict", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload never transfers an owned character", null, tagsOfRule);
#line 38
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 39
      await testRunner.GivenAsync("\"Alice\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 40
      await testRunner.WhenAsync("the companion of \"Bob\" uploads the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 41
      await testRunner.ThenAsync("the claim of \"Bob\" is \"Conflict\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 42
      await testRunner.AndAsync("\"Alice\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A conflicted claim cannot be approved")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "A conflicted claim cannot be approved")]
        public async global::System.Threading.Tasks.Task AConflictedClaimCannotBeApproved()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A conflicted claim cannot be approved", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload never transfers an owned character", null, tagsOfRule);
#line 44
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 45
      await testRunner.GivenAsync("\"Alice\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 46
      await testRunner.AndAsync("the companion of \"Bob\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 47
      await testRunner.WhenAsync("\"Bob\" approves the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 48
      await testRunner.ThenAsync("the claim decision fails with \"Character.Claim.NotPending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 49
      await testRunner.AndAsync("\"Alice\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Approval after another player became owner turns into a conflict")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Approval after another player became owner turns into a conflict")]
        public async global::System.Threading.Tasks.Task ApprovalAfterAnotherPlayerBecameOwnerTurnsIntoAConflict()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Approval after another player became owner turns into a conflict", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("An upload never transfers an owned character", null, tagsOfRule);
#line 51
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 52
      await testRunner.GivenAsync("the companion of \"Alice\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
      await testRunner.AndAsync("the companion of \"Bob\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
      await testRunner.AndAsync("\"Alice\" approved the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
      await testRunner.WhenAsync("\"Bob\" approves the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 56
      await testRunner.ThenAsync("the claim decision fails with \"Character.Claim.OwnedByAnotherUser\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 57
      await testRunner.AndAsync("the claim of \"Bob\" is \"Conflict\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 58
      await testRunner.AndAsync("\"Alice\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableTheoryAttribute(DisplayName="A character is only the player\'s when they own it or are its only claimant")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "A character is only the player\'s when they own it or are its only claimant")]
        [global::Xunit.InlineDataAttribute("\"Alice\" owns the character", "belongs", "7", new string[0])]
        [global::Xunit.InlineDataAttribute("the companion of \"Alice\" uploaded the character", "belongs", "8", new string[0])]
        [global::Xunit.InlineDataAttribute("\"Bob\" owns the character", "doesn\'t belong", "9", new string[0])]
        public async global::System.Threading.Tasks.Task ACharacterIsOnlyThePlayersWhenTheyOwnItOrAreItsOnlyClaimant(string setup, string belongs, string @__pickleIndex, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("setup", setup);
            argumentsOfScenario.Add("belongs", belongs);
            string pickleIndex = @__pickleIndex;
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A character is only the player\'s when they own it or are its only claimant", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Removing a player\'s characters on dev and test deletes only what is theirs alone", null, tagsOfRule);
#line 62
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 63
      await testRunner.GivenAsync(string.Format("{0}", setup), ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 64
      await testRunner.ThenAsync(string.Format("the character {0} only to \"Alice\"", belongs), ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="A character another player claims too isn\'t only the player\'s")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "A character another player claims too isn\'t only the player\'s")]
        public async global::System.Threading.Tasks.Task ACharacterAnotherPlayerClaimsTooIsntOnlyThePlayers()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("A character another player claims too isn\'t only the player\'s", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Removing a player\'s characters on dev and test deletes only what is theirs alone", null, tagsOfRule);
#line 72
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 73
      await testRunner.GivenAsync("the companion of \"Alice\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 74
      await testRunner.AndAsync("the companion of \"Bob\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
      await testRunner.ThenAsync("the character doesn\'t belong only to \"Alice\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Withdrawing a claim on another player\'s character keeps their ownership")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Withdrawing a claim on another player\'s character keeps their ownership")]
        public async global::System.Threading.Tasks.Task WithdrawingAClaimOnAnotherPlayersCharacterKeepsTheirOwnership()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "11";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Withdrawing a claim on another player\'s character keeps their ownership", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Removing a player\'s characters on dev and test deletes only what is theirs alone", null, tagsOfRule);
#line 77
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 78
      await testRunner.GivenAsync("\"Bob\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 79
      await testRunner.AndAsync("the companion of \"Alice\" uploaded the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
      await testRunner.WhenAsync("\"Alice\" withdraws the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 81
      await testRunner.ThenAsync("the claim decision succeeds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 82
      await testRunner.AndAsync("\"Alice\" has no claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 83
      await testRunner.AndAsync("\"Bob\" owns the character", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Withdrawing without a claim is not found")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Character claims")]
        [global::Xunit.TraitAttribute("Description", "Withdrawing without a claim is not found")]
        public async global::System.Threading.Tasks.Task WithdrawingWithoutAClaimIsNotFound()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "12";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Withdrawing without a claim is not found", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = new global::Reqnroll.RuleInfo("Removing a player\'s characters on dev and test deletes only what is theirs alone", null, tagsOfRule);
#line 85
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 86
      await testRunner.WhenAsync("\"Alice\" withdraws the claim", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
      await testRunner.ThenAsync("the claim decision fails with \"Character.Claim.NotFound\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CharacterClaimsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CharacterClaimsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
