// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaidManager.Persistence.EntityFrameworkCore;

#nullable disable

namespace RaidManager.Persistence.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(RaidManagerDbContext))]
    [Migration("20261005072443_AddCharacterSnapshotImport")]
    partial class AddCharacterSnapshotImport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Pivot.Framework.Infrastructure.Abstraction.Outbox.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<string>("EventType")
                        .HasColumnType("text");

                    b.Property<DateTime?>("FailedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("Kind")
                        .HasColumnType("integer");

                    b.Property<string>("LastError")
                        .HasColumnType("text");

                    b.Property<string>("Payload")
                        .HasColumnType("jsonb");

                    b.Property<bool>("Processed")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("ProcessedAtUtc")
                        .HasColumnType("timestamptz");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("OutboxMessages", (string)null);
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Characters.Aggregates.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Class")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Faction")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("GuildName")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOwnershipVerified")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LastAddonSnapshotCapturedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastAddonSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastArmorySynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastCompleteRaidSaveScanAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastIncompleteRaidSaveScanAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastProfessionsSynchronizedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)");

                    b.Property<Guid?>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Race")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("Visibility")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("Realm", "Name")
                        .IsUnique();

                    b.ToTable("Characters", (string)null);
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Communities.Aggregates.Community", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordGuildId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscordGuildId")
                        .IsUnique();

                    b.ToTable("Communities", (string)null);
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Companions.Aggregates.Companion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("LastUploadAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("LastUsedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PairedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("RevokedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("Companions", (string)null);
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Companions.Aggregates.CompanionPairing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(6)
                        .IsUnicode(false)
                        .HasColumnType("character varying(6)");

                    b.Property<Guid?>("CompanionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ComputerLabel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ConfirmedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceCodeHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("RequestedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Code");

                    b.HasIndex("DeviceCodeHash")
                        .IsUnique();

                    b.ToTable("CompanionPairings", (string)null);
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Identity.Aggregates.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DiscordUserId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("TimeZoneId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DiscordUserId")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Raids.Aggregates.Raid", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CommunityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("text");

                    b.Property<DateTime?>("DeletedOnUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("SignupDeadlineUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Requirements", "RaidManager.Domain.Features.Raids.Aggregates.Raid.Requirements#RaidRequirements", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<long>("MaximumCharacterDataAge")
                                .HasColumnType("bigint");

                            b1.Property<int?>("MinimumGearScore")
                                .HasColumnType("integer");

                            b1.Property<bool>("RequiresUnsavedCharacter")
                                .HasColumnType("boolean");
                        });

                    b.HasKey("Id");

                    b.HasIndex("CommunityId", "StartsAtUtc");

                    b.ToTable("Raids", (string)null);
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Characters.Aggregates.Character", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_ModifiedOnUtc");

                            b1.HasKey("CharacterId");

                            b1.ToTable("Characters", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Characters.Aggregates.CharacterClaim", "Claims", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<DateTimeOffset?>("DecidedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("RequestedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("RequestedByUserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId");

                            b1.HasIndex("RequestedByUserId");

                            b1.ToTable("CharacterClaims", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Characters.Aggregates.Loadout", "Loadouts", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int?>("GearScore")
                                .HasColumnType("integer");

                            b1.Property<bool>("IsPrimary")
                                .HasColumnType("boolean");

                            b1.Property<DateTimeOffset>("LastSynchronizedAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<string>("Role")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Source")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<int?>("TalentGroup")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId");

                            b1.ToTable("Loadouts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");

                            b1.OwnsOne("RaidManager.Domain.Features.Characters.ValueObjects.CombatStats", "Stats", b2 =>
                                {
                                    b2.Property<Guid>("LoadoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Agility")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Armor")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("ArmorPenetrationPercent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<int>("ArmorPenetrationRating")
                                        .HasColumnType("integer");

                                    b2.Property<int>("AttackPower")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("BlockPercent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<decimal>("CritPercent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<int>("CritRating")
                                        .HasColumnType("integer");

                                    b2.Property<int>("DefenseSkill")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("DodgePercent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<decimal>("ExpertiseMainHand")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<decimal>("ExpertiseOffHand")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<int>("ExpertiseRating")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("HastePercent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<int>("HasteRating")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Health")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("HitPercent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<int>("HitRating")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Intellect")
                                        .HasColumnType("integer");

                                    b2.Property<decimal>("ParryPercent")
                                        .HasPrecision(9, 4)
                                        .HasColumnType("numeric(9,4)");

                                    b2.Property<int>("ResilienceRating")
                                        .HasColumnType("integer");

                                    b2.Property<int>("SpellPower")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Spirit")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Stamina")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Strength")
                                        .HasColumnType("integer");

                                    b2.HasKey("LoadoutId");

                                    b2.ToTable("Loadouts");

                                    b2.WithOwner()
                                        .HasForeignKey("LoadoutId");
                                });

                            b1.OwnsMany("RaidManager.Domain.Features.Characters.ValueObjects.GearItem", "GearItems", b2 =>
                                {
                                    b2.Property<Guid>("LoadoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<string>("Slot")
                                        .HasMaxLength(32)
                                        .HasColumnType("character varying(32)");

                                    b2.Property<int?>("DisplayId")
                                        .HasColumnType("integer");

                                    b2.Property<int>("ItemId")
                                        .HasColumnType("integer");

                                    b2.Property<int?>("ItemLevel")
                                        .HasColumnType("integer");

                                    b2.Property<string>("ItemLink")
                                        .IsRequired()
                                        .HasMaxLength(512)
                                        .HasColumnType("character varying(512)");

                                    b2.HasKey("LoadoutId", "Slot");

                                    b2.ToTable("LoadoutGearItems", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("LoadoutId");
                                });

                            b1.OwnsOne("RaidManager.Domain.Features.Characters.ValueObjects.TalentConfiguration", "TalentConfiguration", b2 =>
                                {
                                    b2.Property<Guid>("LoadoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("FirstTreePoints")
                                        .HasColumnType("integer");

                                    b2.Property<string>("MajorGlyphIds")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)");

                                    b2.Property<string>("MinorGlyphIds")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)");

                                    b2.Property<int>("SecondTreePoints")
                                        .HasColumnType("integer");

                                    b2.Property<string>("SpecializationName")
                                        .IsRequired()
                                        .HasMaxLength(64)
                                        .HasColumnType("character varying(64)");

                                    b2.Property<string>("TalentCode")
                                        .IsRequired()
                                        .HasMaxLength(128)
                                        .HasColumnType("character varying(128)");

                                    b2.Property<int>("ThirdTreePoints")
                                        .HasColumnType("integer");

                                    b2.HasKey("LoadoutId");

                                    b2.ToTable("Loadouts");

                                    b2.WithOwner()
                                        .HasForeignKey("LoadoutId");
                                });

                            b1.Navigation("GearItems");

                            b1.Navigation("Stats");

                            b1.Navigation("TalentConfiguration")
                                .IsRequired();
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Characters.ValueObjects.Profession", "Professions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("MaxRank")
                                .HasColumnType("integer");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<int>("Rank")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId");

                            b1.ToTable("CharacterProfessions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Characters.ValueObjects.RaidLockout", "RaidLockouts", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Difficulty")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Instance")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<bool>("IsExtended")
                                .HasColumnType("boolean");

                            b1.Property<string>("LockoutId")
                                .HasMaxLength(64)
                                .HasColumnType("character varying(64)");

                            b1.Property<DateTimeOffset>("ResetsAtUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("Id");

                            b1.HasIndex("CharacterId");

                            b1.ToTable("CharacterRaidLockouts", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CharacterId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("Claims");

                    b.Navigation("Loadouts");

                    b.Navigation("Professions");

                    b.Navigation("RaidLockouts");
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Communities.Aggregates.Community", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_ModifiedOnUtc");

                            b1.HasKey("CommunityId");

                            b1.ToTable("Communities", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Communities.Aggregates.CommunityRole", "Roles", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<int>("Permissions")
                                .HasColumnType("integer");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.HasKey("Id");

                            b1.HasIndex("CommunityId");

                            b1.ToTable("CommunityRoles", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Communities.ValueObjects.DiscordRoleMapping", "RoleMappings", b1 =>
                        {
                            b1.Property<Guid>("CommunityId")
                                .HasColumnType("uuid");

                            b1.Property<string>("DiscordRoleId")
                                .HasMaxLength(20)
                                .IsUnicode(false)
                                .HasColumnType("character varying(20)");

                            b1.Property<Guid>("RoleId")
                                .HasColumnType("uuid");

                            b1.HasKey("CommunityId", "DiscordRoleId", "RoleId");

                            b1.ToTable("CommunityRoleMappings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CommunityId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("RoleMappings");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Companions.Aggregates.Companion", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CompanionId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_ModifiedOnUtc");

                            b1.HasKey("CompanionId");

                            b1.ToTable("Companions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanionId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Companions.Aggregates.CompanionPairing", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("CompanionPairingId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_ModifiedOnUtc");

                            b1.HasKey("CompanionPairingId");

                            b1.ToTable("CompanionPairings", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("CompanionPairingId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Identity.Aggregates.User", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_ModifiedOnUtc");

                            b1.HasKey("UserId");

                            b1.ToTable("Users", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("UserId");
                        });

                    b.Navigation("Audit");
                });

            modelBuilder.Entity("RaidManager.Domain.Features.Raids.Aggregates.Raid", b =>
                {
                    b.OwnsOne("Pivot.Framework.Domain.Primitives.AuditInfo", "Audit", b1 =>
                        {
                            b1.Property<Guid>("RaidId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CreatedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_CreatedBy");

                            b1.Property<DateTime>("CreatedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_CreatedOnUtc");

                            b1.Property<string>("ModifiedBy")
                                .HasColumnType("text")
                                .HasColumnName("Audit_ModifiedBy");

                            b1.Property<DateTime?>("ModifiedOnUtc")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("Audit_ModifiedOnUtc");

                            b1.HasKey("RaidId");

                            b1.ToTable("Raids", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RaidId");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Raids.Aggregates.RaidSignup", "Signups", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<string>("Availability")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Comment")
                                .HasColumnType("text");

                            b1.Property<DateTimeOffset?>("LateArrivalUtc")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<Guid>("RaidId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RaidId", "UserId")
                                .IsUnique();

                            b1.ToTable("RaidSignups", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RaidId");

                            b1.OwnsMany("RaidManager.Domain.Features.Raids.ValueObjects.SignupOption", "Options", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<Guid>("CharacterId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("LoadoutId")
                                        .HasColumnType("uuid");

                                    b2.Property<Guid>("RaidSignupId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("Id");

                                    b2.HasIndex("RaidSignupId");

                                    b2.ToTable("RaidSignupOptions", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("RaidSignupId");
                                });

                            b1.Navigation("Options");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Raids.Aggregates.RosterSelection", "RosterSelections", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("CharacterId")
                                .HasColumnType("uuid");

                            b1.Property<int>("GroupNumber")
                                .HasColumnType("integer");

                            b1.Property<Guid>("LoadoutId")
                                .HasColumnType("uuid");

                            b1.Property<int>("Position")
                                .HasColumnType("integer");

                            b1.Property<Guid>("RaidId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("UserId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RaidId", "UserId")
                                .IsUnique();

                            b1.ToTable("RosterSelections", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RaidId");
                        });

                    b.OwnsMany("RaidManager.Domain.Features.Raids.ValueObjects.RaidTarget", "Targets", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Difficulty")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<string>("Instance")
                                .IsRequired()
                                .HasMaxLength(32)
                                .HasColumnType("character varying(32)");

                            b1.Property<Guid>("RaidId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("RaidId");

                            b1.ToTable("RaidTargets", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("RaidId");
                        });

                    b.Navigation("Audit");

                    b.Navigation("RosterSelections");

                    b.Navigation("Signups");

                    b.Navigation("Targets");
                });
#pragma warning restore 612, 618
        }
    }
}
